coverage_service: coveralls
xcodeproj: Commander.xcodeproj
scheme: Commander-Package
configuration: Debug
source_directory: Sources
output_directory: ./
ignore:
  - Sources/commander-sapmle/*
  - Tests/*
