coverage_service: cobertura_xml
xcodeproj: Commander.xcodeproj
scheme: Commander
configuration: Release
source_directory: Sources
output_directory: ./
ignore:
  - Sources/commander-sapmle/*
  - Tests/*
