language: swift
os: osx
osx_image: xcode10
before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
script:
  # - swift package clean
  # - swift test
  - xcodebuild -project Commander.xcodeproj -scheme Commander-Package -sdk macosx10.14 -destination 'platform=macOS,arch=x86_64' build test
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build -t cobertura --exit-code $TRAVIS_TEST_RESULT
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -J 'Commander'
